project_id = "wai-feasibility"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = false
site_url = "http://localhost:5173"
